{{ config(
    materialized='incremental',
    unique_key=['LOAD_DT', 'SUB_AREA_NAME', 'TABLE_NAME', 'TEST_DESC'],
  )
}}

SELECT
   CAST(NULL AS VARCHAR)         AS SUB_AREA_NAME
  ,CAST(NULL AS VARCHAR)         AS TABLE_NAME
  ,CAST(NULL AS DATE)            AS LOAD_DT
  ,CAST(NULL AS DATE)            AS TXN_DT
  ,CAST(NULL AS VARCHAR)         AS TEST_DESC
  ,CAST(NULL AS NUMBER)          AS INTEGRITY_CHK_VIOLATION_ROW_CNT
  ,CAST(NULL AS NUMBER)          AS ROW_CNT
  ,CAST(NULL AS VARCHAR)         AS PASS_FAIL
  ,CAST(NULL AS VARCHAR)         AS SEVERITY
  ,CAST(NULL AS TIMESTAMP_NTZ)   AS RCD_INS_TS
  ,CAST(NULL AS TIMESTAMP_NTZ)   AS RCD_UPD_TS
WHERE 1=0
