version: 2

sources:
  - name: INV_RECON_SRC_STG
    schema: DW_STG_V
    tables:
      - name: V_RECON_F_INV_ILD_B
      - name: V_STG_F_INV_ILD_B

  - name: INV_RECON_SRC_DWH
    schema: DW_DWH
    tables:
      - name: DWH_F_INV_ILD_B

  - name: INV_RECON_SRC_DM
    schema: DM_MERCH
    tables:
      - name: DM_F_MEAS_FACT_ILD_B

  - name: INV_SRC_DM
    schema: DW_DWH_V
    tables:
      - name: V_DWH_F_INV_ILD_B

  - name: INV_SRC_TMP
    schema: DW_DWH
    tables:
      - name: DWH_F_INV_IL_B
